version: "2"

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  settings:
    gofumpt:
      extra-rules: true
    gci:
      sections:
        - standard
        - default
        - blank
        - dot
  exclusions:
    generated: lax

linters:
  default: all
  disable:
    - depguard
    - err113
    - exhaustive
    - exhaustruct
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - interfacebloat
    - ireturn
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - testableexamples
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    cyclop:
      max-complexity: 12
  exclusions:
    generated: lax
    rules:
      - linters:
          - govet
        path: internal/bytes/buffer.go
      - linters:
          - dupl
          - lll
        path: _test\.go
