run:
  tests: false
  deadline: 5m

linters-settings:
  cyclop:
    max-complexity: 12
    skip-tests: true
  gofumpt:
    extra-rules: true

linters:
  enable-all: true
  disable:
    - interfacer # deprecated
    - scopelint # deprecated
    - maligned # deprecated
    - golint # deprecated
    - exhaustive
    - exhaustivestruct
    - forcetypeassert
    - gochecknoglobals
    - gochecknoinits
    - goerr113
    - gomnd
    - ireturn
    - nlreturn
    - varnamelen
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude-rules:
    - path: internal/bytes/buffer.go
      linters:
        - govet
